DROP DATABASE IF EXISTS PROBETHEUS;
CREATE DATABASE PROBETHEUS;
USE PROBETHEUS;

CREATE TABLE USERS (
    ID VARCHAR(64) UNIQUE NOT NULL,
    NAME VARCHAR(100),
    SEX VARCHAR(1),
    SCORE INT,
    PRIMARY KEY (ID)
    );

CREATE TABLE SENSOR (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(200),
    PRIMARY KEY (ID)
    );

CREATE TABLE MEASUREMENTS (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_USER VARCHAR(64) NOT NULL,
    ID_SENSOR INT NOT NULL,
    VALUE_MEASURED DOUBLE NOT NULL,
    UNITS VARCHAR(20) NOT NULL,
    MEASUREMENT_TIME BIGINT NOT NULL,
    LATITUDE DOUBLE NOT NULL,
    LONGITUDE DOUBLE NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES USERS(ID),
    FOREIGN KEY (ID_SENSOR) REFERENCES SENSOR(ID),
    PRIMARY KEY (ID)
    );

INSERT INTO SENSOR(NAME) VALUES ('PH');
INSERT INTO SENSOR(NAME) VALUES ('CONDUCTIVIDAD');
INSERT INTO SENSOR(NAME) VALUES ('TURBIDEZ');
INSERT INTO SENSOR(NAME) VALUES ('COLOR APARENTE');
